# Generated by Django 5.2.17 on 2026-09-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EncryptedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash SHA-256 hexadecimal (64 caracteres) del archivo original sin cifrar.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "encrypted_file",
                    models.FileField(
                        help_text="Archivo binario cifrado en reposo con Fernet (AES-128-CBC + HMAC).",
                        upload_to="encrypted_docs/",
                    ),
                ),
                (
                    "access_code",
                    models.CharField(
                        help_text="Hash PBKDF2 del código secreto de acceso necesario para la verificación.",
                        max_length=128,
                    ),
                ),
                (
                    "encrypted_password",
                    models.TextField(
                        help_text="Contraseña o clave de descifrado cifrada con Fernet (token seguro)."
                    ),
                ),
                (
                    "allowed_emails",
                    models.JSONField(
                        default=list,
                        help_text="Lista de correos electrónicos autorizados en formato JSON (minúsculas).",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de registro y cifrado del documento.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de la última modificación del registro.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Cifrado",
                "verbose_name_plural": "Documentos Cifrados",
                "ordering": ["-created_at"],
            },
        ),
    ]
