# Generated by Django 5.2.17 on 2026-09-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="encrypteddocument",
            name="access_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número total de solicitudes de contraseña o descifrados autorizados.",
                verbose_name="Veces accedido",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="last_accessed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de la última solicitud de contraseña o descifrado.",
                null=True,
                verbose_name="Último acceso",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="last_accessed_by",
            field=models.CharField(
                blank=True,
                help_text="Dirección de correo del último usuario que solicitó la clave.",
                max_length=254,
                null=True,
                verbose_name="Último correo que accedió",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="original_filename",
            field=models.CharField(
                default="documento",
                help_text="Nombre del archivo original subido por el administrador.",
                max_length=255,
                verbose_name="Nombre original del archivo",
            ),
        ),
        migrations.CreateModel(
            name="DocumentAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=254, verbose_name="Correo solicitante"),
                ),
                (
                    "action",
                    models.CharField(
                        default="solicitud_clave",
                        help_text="Tipo de evento: 'solicitud_clave' o 'descifrado'.",
                        max_length=50,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dirección IP"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora de acceso"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="freedec.encrypteddocument",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría de Acceso",
                "verbose_name_plural": "Registros de Auditoría de Accesos",
                "ordering": ["-timestamp"],
            },
        ),
    ]
