# Generated by Django 5.2.17 on 2026-09-26 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0002_encrypteddocument_access_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentaccesslog",
            name="user_agent",
            field=models.TextField(
                blank=True,
                help_text="Cadena de identificación del navegador/cliente para análisis forense.",
                null=True,
                verbose_name="User-Agent",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="admin_encrypted_dek",
            field=models.TextField(
                blank=True,
                help_text="Clave Maestra (DEK) cifrada con FREEDEC_FERNET_KEY para auditoría y descifrado preservado.",
                null=True,
                verbose_name="DEK cifrada para Administrador",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="consumed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento exacto en el que el documento fue consumido y su binario eliminado del disco.",
                null=True,
                verbose_name="Fecha y hora de consumo",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="consumed_by",
            field=models.CharField(
                blank=True,
                help_text="Correo del usuario final que consumió y provocó la destrucción del documento.",
                max_length=254,
                null=True,
                verbose_name="Consumido por",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="digital_envelopes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Sobres digitales multi-usuario en formato JSON: email -> {encrypted_dek, salt, encrypted_password}.",
                verbose_name="Sobres digitales (DEK + KEK)",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="encrypted_file_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash SHA-256 hexadecimal del archivo .enc en reposo para búsqueda directa.",
                max_length=64,
                null=True,
                verbose_name="Hash SHA-256 del archivo cifrado",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="is_consumed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indica si el documento ya ha sido descifrado y consumido por un destinatario final.",
                verbose_name="¿Archivo consumido?",
            ),
        ),
        migrations.AlterField(
            model_name="documentaccesslog",
            name="action",
            field=models.CharField(
                default="solicitud_clave",
                help_text="Tipo de evento: 'solicitud_clave', 'descifrado', 'descifrado_exitoso', 'intento_fallido', 'intento_post_consumo', 'admin_inspeccion_credenciales', 'admin_descifrado_preservado'.",
                max_length=50,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="access_code",
            field=models.CharField(
                help_text="Hash PBKDF2 del código secreto de acceso necesario para la verificación.",
                max_length=128,
                verbose_name="Código de acceso",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="allowed_emails",
            field=models.JSONField(
                default=list,
                help_text="Lista de correos electrónicos autorizados en formato JSON (minúsculas).",
                verbose_name="Correos autorizados",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora de registro y cifrado del documento.",
                verbose_name="Fecha de creación",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="encrypted_file",
            field=models.FileField(
                help_text="Archivo binario cifrado en reposo con Fernet (AES-128-CBC + HMAC).",
                upload_to="encrypted_docs/",
                verbose_name="Archivo cifrado",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="encrypted_password",
            field=models.TextField(
                help_text="Contraseña o clave de descifrado cifrada con Fernet (token seguro).",
                verbose_name="Contraseña cifrada",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="file_hash",
            field=models.CharField(
                db_index=True,
                help_text="Hash SHA-256 hexadecimal (64 caracteres) del archivo original sin cifrar.",
                max_length=64,
                unique=True,
                verbose_name="Hash SHA-256",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Fecha y hora de la última modificación del registro.",
                verbose_name="Fecha de actualización",
            ),
        ),
    ]
