# Generated by Django 5.2.17 on 2026-09-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0003_documentaccesslog_user_agent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="access_code",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="digital_envelopes",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="encrypted_password",
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="user_envelopes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Sobres digitales de la Clave Maestra (DEK) indexados por email normalizado.",
                verbose_name="Sobres digitales de usuario",
            ),
        ),
        migrations.AlterField(
            model_name="documentaccesslog",
            name="action",
            field=models.CharField(
                default="solicitud_acceso",
                help_text="Tipo de evento: 'solicitud_acceso', 'descifrado_completado_burn', 'intento_post_consumo', 'admin_inspeccion_preservada', 'intento_fallido'.",
                max_length=50,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="access_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número total de solicitudes de acceso o descifrados autorizados.",
                verbose_name="Veces accedido",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="consumed_by",
            field=models.EmailField(
                blank=True,
                help_text="Correo del usuario final que consumió y provocó la destrucción del documento.",
                max_length=254,
                null=True,
                verbose_name="Consumido por",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="last_accessed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de la última solicitud de acceso o descifrado.",
                null=True,
                verbose_name="Último acceso",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="last_accessed_by",
            field=models.CharField(
                blank=True,
                help_text="Dirección de correo del último usuario que solicitó el acceso.",
                max_length=254,
                null=True,
                verbose_name="Último correo que accedió",
            ),
        ),
        migrations.CreateModel(
            name="AccessVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        verbose_name="Correo del solicitante",
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Resumen PBKDF2/SHA-256 del token plano enviado por correo.",
                        max_length=128,
                        verbose_name="Hash del token",
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(
                        db_index=True,
                        help_text="Código numérico de 6 dígitos como alternativa al enlace directo.",
                        max_length=6,
                        verbose_name="Código OTP",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de generación"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Caducidad estricta a 15 minutos.",
                        verbose_name="Fecha de caducidad",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el token ya fue consumido para descargar el documento.",
                        verbose_name="¿Utilizado?",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="freedec.encrypteddocument",
                        verbose_name="Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Verificación de Acceso",
                "verbose_name_plural": "Tokens de Verificación de Acceso",
                "ordering": ["-created_at"],
            },
        ),
    ]
