# Generated by Django 5.2.17 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0004_remove_encrypteddocument_access_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encrypteddocument",
            name="file_hash",
            field=models.CharField(
                db_index=True,
                help_text="Hash SHA-256 hexadecimal (64 caracteres) del archivo original sin cifrar.",
                max_length=64,
                verbose_name="Hash SHA-256",
            ),
        ),
    ]
