# Generated by Django 5.2.17 on 2026-09-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0005_alter_encrypteddocument_file_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="encrypteddocument",
            name="burn_policy",
            field=models.CharField(
                choices=[
                    ("FIRST_ACCESS", "Con que solo acceda uno (al primer acceso)"),
                    (
                        "ALL_RECIPIENTS",
                        "Cuando accedan todos (destruir tras el acceso de todos)",
                    ),
                ],
                default="FIRST_ACCESS",
                help_text="Determina si el archivo se destruye al primer acceso de cualquiera o cuando todos los destinatarios hayan accedido.",
                max_length=20,
                verbose_name="Política de destrucción",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="consumed_recipients",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de correos autorizados que ya han descargado su copia.",
                verbose_name="Destinatarios que han consumido",
            ),
        ),
        migrations.AlterField(
            model_name="documentaccesslog",
            name="action",
            field=models.CharField(
                default="solicitud_acceso",
                help_text="Tipo de evento: 'solicitud_acceso', 'descifrado_completado_burn', 'descifrado_parcial_preservado', 'intento_post_consumo', 'admin_inspeccion_preservada', 'intento_fallido'.",
                max_length=50,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="consumed_by",
            field=models.CharField(
                blank=True,
                help_text="Correo del usuario final o resumen de destinatarios que consumieron y provocaron la destrucción del documento.",
                max_length=254,
                null=True,
                verbose_name="Consumido por",
            ),
        ),
    ]
