# Generated by Django 5.2.17 on 2026-09-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0006_encrypteddocument_burn_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentaccesslog",
            name="action",
            field=models.CharField(
                default="solicitud_acceso",
                help_text="Tipo de evento: 'solicitud_acceso', 'descifrado_completado_burn', 'descifrado_parcial_preservado', 'reactivacion_documento', 'intento_post_consumo', 'admin_inspeccion_preservada', 'intento_fallido'.",
                max_length=50,
                verbose_name="Acción",
            ),
        ),
    ]
