# Generated by Django 5.2.17 on 2026-09-27 07:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0007_alter_documentaccesslog_action"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessverificationtoken",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Token de Verificación OTP",
                "verbose_name_plural": "Tokens de Verificación OTP",
            },
        ),
        migrations.AlterModelOptions(
            name="documentaccesslog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Registro de Auditoría de Acceso",
                "verbose_name_plural": "Registros de Auditoría de Accesos",
            },
        ),
        migrations.AlterModelOptions(
            name="encrypteddocument",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "can_audit_download",
                        "Puede realizar descarga de auditoría administrativa",
                    )
                ],
                "verbose_name": "Documento Cifrado",
                "verbose_name_plural": "Documentos Cifrados",
            },
        ),
        migrations.RemoveField(
            model_name="accessverificationtoken",
            name="token_hash",
        ),
        migrations.RemoveField(
            model_name="documentaccesslog",
            name="timestamp",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="access_count",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="admin_encrypted_dek",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="burn_policy",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="consumed_recipients",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="encrypted_file_hash",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="last_accessed_at",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="last_accessed_by",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="encrypteddocument",
            name="user_envelopes",
        ),
        migrations.AddField(
            model_name="accessverificationtoken",
            name="failed_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Contador de intentos fallidos. Se revoca al alcanzar 3.",
                verbose_name="Intentos fallidos",
            ),
        ),
        migrations.AddField(
            model_name="documentaccesslog",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha y hora"
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="encrypted_dek",
            field=models.TextField(
                default="",
                help_text="DEK cifrada internamente con settings.FREEDEC_FERNET_KEY.",
                verbose_name="Clave Maestra de Datos (DEK) cifrada",
            ),
        ),
        migrations.AlterField(
            model_name="accessverificationtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AlterField(
            model_name="accessverificationtoken",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_tokens",
                to="freedec.encrypteddocument",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="accessverificationtoken",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=254,
                verbose_name="Correo oficial del solicitante",
            ),
        ),
        migrations.AlterField(
            model_name="accessverificationtoken",
            name="is_used",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el token ya fue consumido o revocado.",
                verbose_name="¿Utilizado?",
            ),
        ),
        migrations.AlterField(
            model_name="accessverificationtoken",
            name="otp_code",
            field=models.CharField(
                help_text="Código numérico de 6 dígitos generado criptográficamente.",
                max_length=6,
                verbose_name="Código OTP",
            ),
        ),
        migrations.AlterField(
            model_name="documentaccesslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("solicitud_otp", "Solicitud de OTP"),
                    ("otp_enviado", "OTP enviado al solicitante"),
                    (
                        "descifrado_exitoso_burn",
                        "Descifrado exitoso y destrucción segura (Burn-After-Read)",
                    ),
                    ("intento_post_consumo", "Intento de acceso post-consumo"),
                    ("otp_invalido_bloqueado", "OTP inválido / Bloqueado por intentos"),
                    (
                        "admin_descarga_preservada",
                        "Descarga de auditoría administrativa preservada",
                    ),
                ],
                max_length=50,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="documentaccesslog",
            name="email",
            field=models.CharField(
                max_length=254, verbose_name="Correo del solicitante"
            ),
        ),
        migrations.AlterField(
            model_name="documentaccesslog",
            name="user_agent",
            field=models.TextField(blank=True, null=True, verbose_name="User-Agent"),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="allowed_emails",
            field=models.JSONField(
                default=list,
                help_text="Lista de correos autorizados en minúsculas.",
                verbose_name="Correos autorizados",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="consumed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento exacto en el que el documento fue canjeado.",
                null=True,
                verbose_name="Fecha y hora del canje",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="consumed_by",
            field=models.EmailField(
                blank=True,
                help_text="Correo del usuario que retiró el documento.",
                max_length=254,
                null=True,
                verbose_name="Consumido por",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Marca temporal de creación del registro.",
                verbose_name="Fecha de alta",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="encrypted_file",
            field=models.FileField(
                help_text="Archivo binario cifrado en reposo con la DEK.",
                upload_to="encrypted_docs/%Y/%m/",
                verbose_name="Archivo cifrado",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="file_hash",
            field=models.CharField(
                db_index=True,
                help_text="Hash SHA-256 hexadecimal (64 caracteres) del archivo original.",
                max_length=64,
                unique=True,
                verbose_name="Hash SHA-256",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="is_consumed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indica si el documento ya fue canjeado y destruido del almacenamiento.",
                verbose_name="¿Documento consumido?",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="original_filename",
            field=models.CharField(
                default="documento",
                help_text="Nombre del archivo original cargado en el sistema.",
                max_length=255,
                verbose_name="Nombre original del documento",
            ),
        ),
    ]
