# Generated by Django 5.2.17 on 2026-09-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0008_alter_accessverificationtoken_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encrypteddocument",
            name="burn_policy",
            field=models.CharField(
                choices=[
                    ("FIRST_ACCESS", "Con que solo acceda uno (al primer acceso)"),
                    (
                        "ALL_RECIPIENTS",
                        "Cuando accedan todos (destruir tras el acceso de todos)",
                    ),
                ],
                default="FIRST_ACCESS",
                help_text="Determina si se destruye al primer acceso o tras el acceso de todos.",
                max_length=20,
                verbose_name="Política de destrucción",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="consumed_recipients",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de correos que ya han descargado su copia individual.",
                verbose_name="Destinatarios que han consumido",
            ),
        ),
        migrations.AddField(
            model_name="encrypteddocument",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Marca temporal de la última actualización.",
                verbose_name="Fecha de actualización",
            ),
        ),
        migrations.AlterField(
            model_name="documentaccesslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("solicitud_otp", "Solicitud de OTP"),
                    ("otp_enviado", "OTP enviado al solicitante"),
                    (
                        "descifrado_exitoso_burn",
                        "Descifrado exitoso y destrucción segura (Burn-After-Read)",
                    ),
                    (
                        "descifrado_parcial_preservado",
                        "Descifrado parcial (preservado para restantes destinatarios)",
                    ),
                    (
                        "reactivacion_documento",
                        "Reactivación y re-cifrado de documento",
                    ),
                    ("intento_post_consumo", "Intento de acceso post-consumo"),
                    ("otp_invalido_bloqueado", "OTP inválido / Bloqueado por intentos"),
                    (
                        "admin_descarga_preservada",
                        "Descarga de auditoría administrativa preservada",
                    ),
                ],
                max_length=50,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="consumed_by",
            field=models.CharField(
                blank=True,
                help_text="Correo del usuario o resumen de destinatarios que retiraron el documento.",
                max_length=254,
                null=True,
                verbose_name="Consumido por",
            ),
        ),
    ]
