# Generated by Django 5.2.17 on 2026-09-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0009_encrypteddocument_burn_policy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encrypteddocument",
            name="description",
            field=models.TextField(
                blank=True,
                default="Documento confidencial tramitado a través de la pasarela segura Freedec.",
                help_text="Descripción informativa o motivo confidencial para las notificaciones por correo.",
                verbose_name="Descripción del documento",
            ),
        ),
    ]
