# Generated by Django 5.2.17 on 2026-09-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freedec", "0010_encrypteddocument_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentaccesslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("solicitud_otp", "Solicitud de código de verificación"),
                    ("otp_enviado", "Código de verificación enviado"),
                    (
                        "descifrado_exitoso_burn",
                        "Descarga completada y retirada de la pasarela",
                    ),
                    (
                        "descifrado_parcial_preservado",
                        "Descarga individual completada (en espera de restantes destinatarios)",
                    ),
                    ("reactivacion_documento", "Reactivación de documento"),
                    ("intento_post_consumo", "Acceso a documento no disponible"),
                    (
                        "otp_invalido_bloqueado",
                        "Código bloqueado por intentos fallidos",
                    ),
                    (
                        "admin_descarga_preservada",
                        "Descarga de auditoría administrativa",
                    ),
                ],
                max_length=50,
                verbose_name="Acción",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="burn_policy",
            field=models.CharField(
                choices=[
                    ("FIRST_ACCESS", "Descarga única (primer acceso)"),
                    ("ALL_RECIPIENTS", "Disponible para todos los destinatarios"),
                ],
                default="FIRST_ACCESS",
                help_text="Determina si se destruye al primer acceso o tras el acceso de todos.",
                max_length=20,
                verbose_name="Política de destrucción",
            ),
        ),
        migrations.AlterField(
            model_name="encrypteddocument",
            name="description",
            field=models.TextField(
                blank=True,
                default="Documento confidencial compartido a través de la pasarela segura Freedec.",
                help_text="Descripción informativa para las notificaciones por correo electrónico.",
                verbose_name="Descripción del documento",
            ),
        ),
    ]
